# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veirox < Formula
  desc "Veirox CLI — DevOps automation as MCP tools for your agent"
  homepage "https://veirox.com"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/veirox-cloud/veirox-dist/releases/download/v0.1.0/veirox_0.1.0_darwin_amd64.tar.gz"
      sha256 "c4d11bc59b77795cb7c67a2895d2cc879f13e29b4dd99a753a23492f0ea7d9a3"

      define_method(:install) do
        bin.install "veirox"
        generate_completions_from_executable(bin/"veirox", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/veirox-cloud/veirox-dist/releases/download/v0.1.0/veirox_0.1.0_darwin_arm64.tar.gz"
      sha256 "4b0ec6867272ceef2efdfe9ab1e0635ddc59a043390d44fd99093b727c2e27e4"

      define_method(:install) do
        bin.install "veirox"
        generate_completions_from_executable(bin/"veirox", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/veirox-cloud/veirox-dist/releases/download/v0.1.0/veirox_0.1.0_linux_amd64.tar.gz"
      sha256 "1b6a2885775fdda61382bb2287e610bf14bf60cd3ea2e93af683d38df98e63d0"
      define_method(:install) do
        bin.install "veirox"
        generate_completions_from_executable(bin/"veirox", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/veirox-cloud/veirox-dist/releases/download/v0.1.0/veirox_0.1.0_linux_arm64.tar.gz"
      sha256 "c1539ae0d40c2f8f5de322bf2aa257213fd23e4f208cc7ca9fef87c9b11147fd"
      define_method(:install) do
        bin.install "veirox"
        generate_completions_from_executable(bin/"veirox", "completion")
      end
    end
  end

  test do
    assert_match "veirox", shell_output("#{bin}/veirox version --short")
  end
end
